const runs = [
  {
    subject: 'ADOPTI-ID 7F4A2C',
    species: 'Canine · Medium · Mixed breed',
    featured: false,
    timeline: [
      'T0 Intake          Apr 03 · 09:12 PT · Origin: Shelter A',
      'T1 Match           Apr 03 · 11:47 PT · DSRE confidence 0.84',
      'T2 Committed       Apr 04 · 08:30 PT · Partner: Rescue B',
      'T3 Dispatched      Apr 05 · 07:00 PT · Transport leg 1',
      'T4 In-Transit      Apr 05 · 07:00 PT → 13:42 PT',
      'T5 Delivered       Apr 05 · 13:42 PT · GPS + biometric verified',
      'T6 In-Placement    Apr 05 · 13:42 PT · 90-day window opened',
      '',
      'Day 3 check-in     Apr 08 · stable',
      'Day 7 check-in     Apr 12 · stable',
      'Day 14 check-in    Apr 19 · stable',
      'Day 30 check-in    May 05 · stable',
      'Day 60 check-in    Jun 04 · stable',
      'Day 90 verification Jul 04 · 3-condition AND gate ✓',
      '  C1 No return: ✓ · C2 Health cert: ✓ · C3 License reg: ✓',
    ],
    outcome: ['OUTCOME: Full settlement triggered', 'Settlement instruction transmitted to financial intermediary', 'DSRE weight update: Partner B success rate +0.03'],
    claims_demonstrated: 'Baseline PEX Claim 25 transition audit · OVESS Claim 23 Day-90 settlement',
  },
  {
    subject: 'ADOPTI-ID 3B81D9',
    species: 'Canine · Large · Pit mix · Behavioral flag: resource guarding',
    featured: true,
    timeline: [
      'T0 Intake          Mar 14 · 14:22 PT · Origin: Shelter A',
      'T1 Match           Mar 14 · 16:55 PT · DSRE confidence 0.71',
      'T2 Committed       Mar 15 · 09:10 PT · Partner: Foster X',
      'T3 Dispatched      Mar 16 · 08:45 PT',
      'T4 Delivered       Mar 16 · 11:18 PT',
      'T5 In-Placement    Mar 16 · 11:18 PT',
      '',
      'Day 3 check-in     Mar 19 · stable',
      'Day 7 check-in     Mar 23 · stable',
      'Day 14 check-in    Mar 30 · FAILED · return event opened',
      '  Return reason code: behavior incompatible with household pet',
      '',
      '  PEX EXCEPTION TRIGGERED',
      '  · Re-routing request transmitted to DSRE',
      '  · Partner Foster X excluded from candidate pool for 90 days',
      '  · Subject returned to Shelter A · PIR re-opened',
      '',
      "T0' Re-intake      Mar 31 · 10:00 PT · prior PIR continues — no new record",
      "T1' Re-match       Mar 31 · 14:30 PT · DSRE confidence 0.68",
      '                     · Trajectory classifier: Rising (Partner Y +14% Q1)',
      '                     · Behavioral flag from return event factored in',
      "T2' Committed      Apr 02 · 08:15 PT · Partner: Rescue Y (behavioral specialist)",
      "T3'–T5'            Apr 03 · transport completed · in-placement",
      '',
      'Day 3 check-in     Apr 06 · stable',
      'Day 14 check-in    Apr 17 · stable',
      'Day 30 check-in    May 03 · stable',
      'Day 60 check-in    Jun 02 · stable',
      'Day 90 verification Jul 02 · 3-condition AND gate ✓',
    ],
    outcome: ['OUTCOME: Full settlement triggered (to Partner Y, not Partner X)', 'DSRE weight update: Partner X success rate −0.04 · Partner Y +0.03'],
    claims_demonstrated: 'PEX Claim 25 (exception state) · DSRE Claim 22 (re-routing) · OVESS Claim 23 (verified outcome on retry)',
  },
  {
    subject: 'PROVISIONAL-ID PT-0042 (no PIR created)',
    species: 'Pre-intake event: Inbound surrender call · TCPA-compliant channel',
    featured: false,
    timeline: [
      'T-1  Inbound call  Feb 08 · 17:42 PT',
      '     Caller intent: Owner surrender · stated reason: lost housing',
      '     PVDTS intent classifier: SURRENDER (confidence 0.91)',
      '     Diversion risk score: 0.83 (above threshold 0.65)',
      '',
      "T-1' Resource match",
      '     · Emergency boarding voucher · 30-day program',
      '     · Pet food bank · weekly pickup',
      '     · Veterinary care · low-cost spay/neuter referral',
      '',
      "T-1'' Referral delivered",
      '     SMS sent · voicemail playback completed · email confirmation',
    ],
    outcome: ['OUTCOME: No physical intake', "Pre-intake event record appended to PIR for caller's animal", '  · If animal ever enters any participating shelter, this record loads', '  · Surrender-risk flag set for next 12 months as DSRE input'],
    claims_demonstrated: 'PVDTS Claims 16–18 (pre-intake interception, resource ranking, pre-intake event record)',
  },
  {
    subject: 'ADOPTI-ID 9C2E18 (canonical) ← merged from PT-0107 (provisional)',
    species: 'Cross-organization identity merge · PCSIA + TMRRE',
    featured: false,
    timeline: [
      'Day -42  Stray intake at Shelter A · no microchip · provisional ID PT-0107',
      '         · Photo + behavioral assessment + GPS recorded',
      '         · Held 5 days · no owner claim · transferred to Rescue B',
      '',
      'Day -37  Rescue B scans subject · microchip detected (registered to original',
      '         owner via 24PetWatch · ISO 11784/11785 ID 982000123456789)',
      '         · Canonical biometric identifier resolved',
      '         · PCSIA merge: PT-0107 history → ADOPTI-ID 9C2E18',
      '',
      'TMRRE reconciliation triggered',
      '  Source 1: Shelter A intake record (custody-period weight 1.0)',
      '  Source 2: Rescue B scan record (custody-period weight 1.0)',
      '  Source 3: 24PetWatch registration (custody-period weight 0.4)',
      '  Conflict: Source 3 lists "Charlie / male / 4 years" — Sources 1 & 2 list',
      '            "unknown / male / approx 6 years"',
      '  Resolution: Custody-weighted vote retains breed + sex; flags age conflict',
      '              for human review (low-confidence below 0.75 threshold)',
      '  Audit trail appended',
      '',
      'T0 onward  Standard placement flow continues with merged history intact',
    ],
    outcome: ['OUTCOME: Subject placed with original owner (verified via 24PetWatch reunification)'],
    claims_demonstrated: 'PCSIA Claim 21 (provisional → canonical merge) · TMRRE Claim 24 (custody-period multiplier + five similarity dimensions)',
  },
  {
    subject: 'ADOPTI-ID A4F09B',
    species: 'Feline · Senior · Medical: chronic kidney disease',
    featured: false,
    timeline: [
      'T0 Intake          Jan 12 · 10:30 PT · Origin: Shelter A',
      'T1–T5              Standard flow · placed Jan 16 with Foster Z (senior cat specialist)',
      '',
      'Day 3, 7, 14, 30 check-ins: stable',
      'Day 60 check-in    Mar 17 · FAILED',
      '  Return reason code: medical-deterioration · owner unable to continue care',
      '  Return event opened · subject returned to Shelter A',
      '',
      'OVESS observation window evaluated at Day 60:',
      '  · No return (C1): FAILED at Day 60',
      '  · Health cert (C2): satisfied through Day 59',
      '  · License reg (C3): satisfied',
      '  Three-condition AND gate at Day 90: NOT SATISFIED',
      '',
      'PARTIAL SETTLEMENT TRIGGERED (Day 60-90 tier rule)',
      '  · Partner Z receives prorated settlement (60/90 = 67% of full)',
      '  · Failure record appended to PIR with dispute flag',
      '  · No DSRE weight penalty (medical-deterioration is not partner failure)',
    ],
    outcome: ['OUTCOME: Partial settlement · subject re-entered routing flow'],
    claims_demonstrated: 'OVESS Claim 23 partial-settlement tier · PEX state machine handling of failed verification',
  },
];

function renderRunHistoryCard(run) {
  const article = document.createElement('article');
  article.className = `run-card${run.featured ? ' featured' : ''}`;
  article.innerHTML = `
    <div class="run-card-header">
      <p>Subject</p>
      <h3>${run.subject}</h3>
      <span>${run.species}</span>
    </div>
    <pre>${[...run.timeline, '', ...run.outcome].join('\n')}</pre>
    <footer>Patent claims demonstrated: ${run.claims_demonstrated}</footer>
  `;
  return article;
}

const runHistory = document.querySelector('#run-history');
runs.forEach((run) => runHistory?.appendChild(renderRunHistoryCard(run)));
